
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1_compi.analizadores;

import java_cup.runtime.*;
import java.util.*;
import com.example.practica1_compi.models.*;
import android.util.Log;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\004\000\002\002\005\000\002\003" +
    "\005\000\002\004\004\000\002\004\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\014\003\000\002" +
    "\015\004\000\002\015\003\000\002\016\003\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\006\006" +
    "\000\002\006\004\000\002\007\005\000\002\010\004\000" +
    "\002\010\004\000\002\011\004\000\002\012\011\000\002" +
    "\012\012\000\002\013\011\000\002\013\012\000\002\017" +
    "\003\000\002\020\004\000\002\020\003\000\002\021\005" +
    "\000\002\021\007\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\022\003\000\002" +
    "\023\005\000\002\023\005\000\002\023\003\000\002\024" +
    "\005\000\002\024\005\000\002\024\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\005\000\002\026\005\000" +
    "\002\026\005\000\002\026\005\000\002\026\005\000\002" +
    "\026\005\000\002\026\005\000\002\026\005\000\002\026" +
    "\005\000\002\026\004\000\002\026\005\000\002\027\007" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\156\000\004\011\006\001\002\000\004\004\135\001" +
    "\002\000\004\002\134\001\002\000\016\013\014\014\022" +
    "\017\020\022\010\023\015\047\021\001\002\000\020\012" +
    "\ufff7\013\ufff7\014\ufff7\017\ufff7\022\ufff7\023\ufff7\047\ufff7" +
    "\001\002\000\012\044\050\046\132\047\032\050\030\001" +
    "\002\000\020\012\ufffd\013\ufffd\014\ufffd\017\ufffd\022\ufffd" +
    "\023\ufffd\047\ufffd\001\002\000\020\012\ufff8\013\ufff8\014" +
    "\ufff8\017\ufff8\022\ufff8\023\ufff8\047\ufff8\001\002\000\020" +
    "\012\ufffb\013\ufffb\014\ufffb\017\ufffb\022\ufffb\023\ufffb\047" +
    "\ufffb\001\002\000\004\047\127\001\002\000\004\047\126" +
    "\001\002\000\020\012\ufffc\013\ufffc\014\ufffc\017\ufffc\022" +
    "\ufffc\023\ufffc\047\ufffc\001\002\000\020\012\ufff9\013\ufff9" +
    "\014\ufff9\017\ufff9\022\ufff9\023\ufff9\047\ufff9\001\002\000" +
    "\004\044\116\001\002\000\004\024\114\001\002\000\004" +
    "\044\027\001\002\000\020\012\025\013\014\014\022\017" +
    "\020\022\010\023\015\047\021\001\002\000\020\012\ufffa" +
    "\013\ufffa\014\ufffa\017\ufffa\022\ufffa\023\ufffa\047\ufffa\001" +
    "\002\000\004\004\uffff\001\002\000\020\012\ufffe\013\ufffe" +
    "\014\ufffe\017\ufffe\022\ufffe\023\ufffe\047\ufffe\001\002\000" +
    "\012\041\034\044\035\047\032\050\030\001\002\000\066" +
    "\002\uffd5\005\uffd5\012\uffd5\013\uffd5\014\uffd5\016\uffd5\017" +
    "\uffd5\021\uffd5\022\uffd5\023\uffd5\025\uffd5\026\uffd5\027\uffd5" +
    "\030\uffd5\031\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5\036" +
    "\uffd5\037\uffd5\040\uffd5\042\uffd5\043\uffd5\045\uffd5\047\uffd5" +
    "\001\002\000\066\002\uffd6\005\uffd6\012\uffd6\013\uffd6\014" +
    "\uffd6\016\uffd6\017\uffd6\021\uffd6\022\uffd6\023\uffd6\025\uffd6" +
    "\026\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\033\uffd6\034" +
    "\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\042\uffd6\043\uffd6" +
    "\045\uffd6\047\uffd6\001\002\000\066\002\uffd4\005\uffd4\012" +
    "\uffd4\013\uffd4\014\uffd4\016\uffd4\017\uffd4\021\uffd4\022\uffd4" +
    "\023\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032" +
    "\uffd4\033\uffd4\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4" +
    "\042\uffd4\043\uffd4\045\uffd4\047\uffd4\001\002\000\010\037" +
    "\072\040\073\045\077\001\002\000\012\041\034\044\035" +
    "\047\032\050\030\001\002\000\012\041\034\044\035\047" +
    "\032\050\030\001\002\000\066\002\uffd9\005\uffd9\012\uffd9" +
    "\013\uffd9\014\uffd9\016\uffd9\017\uffd9\021\uffd9\022\uffd9\023" +
    "\uffd9\025\uffd9\026\uffd9\027\062\030\063\031\uffd9\032\uffd9" +
    "\033\uffd9\034\uffd9\035\uffd9\036\uffd9\037\uffd9\040\uffd9\042" +
    "\uffd9\043\uffd9\045\uffd9\047\uffd9\001\002\000\022\025\041" +
    "\026\040\031\043\032\045\033\046\034\047\035\044\036" +
    "\042\001\002\000\010\044\050\047\032\050\030\001\002" +
    "\000\010\044\050\047\032\050\030\001\002\000\010\044" +
    "\050\047\032\050\030\001\002\000\010\044\050\047\032" +
    "\050\030\001\002\000\010\044\050\047\032\050\030\001" +
    "\002\000\010\044\050\047\032\050\030\001\002\000\010" +
    "\044\050\047\032\050\030\001\002\000\010\044\050\047" +
    "\032\050\030\001\002\000\010\044\050\047\032\050\030" +
    "\001\002\000\014\025\041\026\040\037\uffcf\040\uffcf\045" +
    "\uffcf\001\002\000\010\025\041\026\040\045\053\001\002" +
    "\000\066\002\uffd3\005\uffd3\012\uffd3\013\uffd3\014\uffd3\016" +
    "\uffd3\017\uffd3\021\uffd3\022\uffd3\023\uffd3\025\uffd3\026\uffd3" +
    "\027\uffd3\030\uffd3\031\uffd3\032\uffd3\033\uffd3\034\uffd3\035" +
    "\uffd3\036\uffd3\037\uffd3\040\uffd3\042\uffd3\043\uffd3\045\uffd3" +
    "\047\uffd3\001\002\000\014\025\041\026\040\037\uffd0\040" +
    "\uffd0\045\uffd0\001\002\000\014\025\041\026\040\037\uffd1" +
    "\040\uffd1\045\uffd1\001\002\000\014\025\041\026\040\037" +
    "\uffce\040\uffce\045\uffce\001\002\000\014\025\041\026\040" +
    "\037\uffd2\040\uffd2\045\uffd2\001\002\000\014\025\041\026" +
    "\040\037\uffcd\040\uffcd\045\uffcd\001\002\000\066\002\uffdb" +
    "\005\uffdb\012\uffdb\013\uffdb\014\uffdb\016\uffdb\017\uffdb\021" +
    "\uffdb\022\uffdb\023\uffdb\025\uffdb\026\uffdb\027\062\030\063" +
    "\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\uffdb\036\uffdb\037" +
    "\uffdb\040\uffdb\042\uffdb\043\uffdb\045\uffdb\047\uffdb\001\002" +
    "\000\010\044\050\047\032\050\030\001\002\000\010\044" +
    "\050\047\032\050\030\001\002\000\066\002\uffd7\005\uffd7" +
    "\012\uffd7\013\uffd7\014\uffd7\016\uffd7\017\uffd7\021\uffd7\022" +
    "\uffd7\023\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7" +
    "\032\uffd7\033\uffd7\034\uffd7\035\uffd7\036\uffd7\037\uffd7\040" +
    "\uffd7\042\uffd7\043\uffd7\045\uffd7\047\uffd7\001\002\000\066" +
    "\002\uffd8\005\uffd8\012\uffd8\013\uffd8\014\uffd8\016\uffd8\017" +
    "\uffd8\021\uffd8\022\uffd8\023\uffd8\025\uffd8\026\uffd8\027\uffd8" +
    "\030\uffd8\031\uffd8\032\uffd8\033\uffd8\034\uffd8\035\uffd8\036" +
    "\uffd8\037\uffd8\040\uffd8\042\uffd8\043\uffd8\045\uffd8\047\uffd8" +
    "\001\002\000\066\002\uffda\005\uffda\012\uffda\013\uffda\014" +
    "\uffda\016\uffda\017\uffda\021\uffda\022\uffda\023\uffda\025\uffda" +
    "\026\uffda\027\062\030\063\031\uffda\032\uffda\033\uffda\034" +
    "\uffda\035\uffda\036\uffda\037\uffda\040\uffda\042\uffda\043\uffda" +
    "\045\uffda\047\uffda\001\002\000\010\037\072\040\073\045" +
    "\071\001\002\000\024\025\041\026\040\031\043\032\045" +
    "\033\046\034\047\035\044\036\042\045\053\001\002\000" +
    "\010\037\uffc9\040\uffc9\045\uffc9\001\002\000\012\041\034" +
    "\044\035\047\032\050\030\001\002\000\012\041\034\044" +
    "\035\047\032\050\030\001\002\000\010\037\072\040\uffcb" +
    "\045\uffcb\001\002\000\010\037\uffcc\040\uffcc\045\uffcc\001" +
    "\002\000\010\037\uffca\040\uffca\045\uffca\001\002\000\004" +
    "\015\100\001\002\000\012\013\014\022\010\023\015\047" +
    "\021\001\002\000\020\012\ufff4\013\ufff4\016\ufff4\021\ufff4" +
    "\022\ufff4\023\ufff4\047\ufff4\001\002\000\020\012\ufff6\013" +
    "\014\016\ufff6\021\ufff6\022\010\023\015\047\021\001\002" +
    "\000\020\012\ufff2\013\ufff2\016\ufff2\021\ufff2\022\ufff2\023" +
    "\ufff2\047\ufff2\001\002\000\006\012\111\016\110\001\002" +
    "\000\020\012\ufff3\013\ufff3\016\ufff3\021\ufff3\022\ufff3\023" +
    "\ufff3\047\ufff3\001\002\000\020\012\ufff0\013\ufff0\016\ufff0" +
    "\021\ufff0\022\ufff0\023\ufff0\047\ufff0\001\002\000\020\012" +
    "\ufff1\013\ufff1\016\ufff1\021\ufff1\022\ufff1\023\ufff1\047\ufff1" +
    "\001\002\000\020\012\uffe9\013\uffe9\014\uffe9\017\uffe9\022" +
    "\uffe9\023\uffe9\047\uffe9\001\002\000\004\014\112\001\002" +
    "\000\020\012\uffe8\013\uffe8\014\uffe8\017\uffe8\022\uffe8\023" +
    "\uffe8\047\uffe8\001\002\000\020\012\ufff5\013\ufff5\016\ufff5" +
    "\021\ufff5\022\ufff5\023\ufff5\047\ufff5\001\002\000\010\044" +
    "\050\047\032\050\030\001\002\000\030\012\uffed\013\uffed" +
    "\014\uffed\016\uffed\017\uffed\021\uffed\022\uffed\023\uffed\025" +
    "\041\026\040\047\uffed\001\002\000\012\041\034\044\035" +
    "\047\032\050\030\001\002\000\010\037\072\040\073\045" +
    "\120\001\002\000\004\020\121\001\002\000\012\013\014" +
    "\022\010\023\015\047\021\001\002\000\006\012\124\021" +
    "\123\001\002\000\020\012\uffe7\013\uffe7\014\uffe7\017\uffe7" +
    "\022\uffe7\023\uffe7\047\uffe7\001\002\000\004\017\125\001" +
    "\002\000\020\012\uffe6\013\uffe6\014\uffe6\017\uffe6\022\uffe6" +
    "\023\uffe6\047\uffe6\001\002\000\024\012\uffea\013\uffea\014" +
    "\uffea\016\uffea\017\uffea\021\uffea\022\uffea\023\uffea\047\uffea" +
    "\001\002\000\026\012\uffee\013\uffee\014\uffee\016\uffee\017" +
    "\uffee\021\uffee\022\uffee\023\uffee\024\130\047\uffee\001\002" +
    "\000\010\044\050\047\032\050\030\001\002\000\030\012" +
    "\uffef\013\uffef\014\uffef\016\uffef\017\uffef\021\uffef\022\uffef" +
    "\023\uffef\025\041\026\040\047\uffef\001\002\000\024\012" +
    "\uffec\013\uffec\014\uffec\016\uffec\017\uffec\021\uffec\022\uffec" +
    "\023\uffec\047\uffec\001\002\000\030\012\uffeb\013\uffeb\014" +
    "\uffeb\016\uffeb\017\uffeb\021\uffeb\022\uffeb\023\uffeb\025\041" +
    "\026\040\047\uffeb\001\002\000\004\002\001\001\002\000" +
    "\004\005\136\001\002\000\004\024\143\001\002\000\006" +
    "\002\uffe3\005\uffe3\001\002\000\004\002\000\001\002\000" +
    "\006\002\uffe5\005\136\001\002\000\006\002\uffe4\005\uffe4" +
    "\001\002\000\016\006\146\007\145\010\144\044\050\047" +
    "\032\050\147\001\002\000\010\002\uffe0\005\uffe0\043\uffe0" +
    "\001\002\000\010\002\uffdd\005\uffdd\043\uffdd\001\002\000" +
    "\010\002\uffde\005\uffde\043\uffde\001\002\000\022\002\uffdc" +
    "\005\uffdc\025\uffd5\026\uffd5\027\uffd5\030\uffd5\042\uffd5\043" +
    "\uffdc\001\002\000\010\025\041\026\040\042\155\001\002" +
    "\000\010\002\uffdf\005\uffdf\043\uffdf\001\002\000\010\002" +
    "\uffe2\005\uffe2\043\153\001\002\000\004\050\154\001\002" +
    "\000\006\002\uffe1\005\uffe1\001\002\000\010\044\050\047" +
    "\032\050\030\001\002\000\010\025\041\026\040\042\157" +
    "\001\002\000\010\044\050\047\032\050\030\001\002\000" +
    "\014\002\uffc8\005\uffc8\025\041\026\040\043\uffc8\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\156\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\004\022\005\010\006\015" +
    "\007\012\010\023\011\016\012\011\013\006\001\001\000" +
    "\002\001\001\000\010\023\132\024\035\025\030\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\005\025\006\015\007\012\010\023\011\016" +
    "\012\011\013\006\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\023\036\024\035\025\030" +
    "\026\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\023\036\024\035" +
    "\025\030\026\075\001\001\000\012\023\067\024\035\025" +
    "\030\026\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\024\065\025\030\001\001\000\006\024\060\025" +
    "\030\001\001\000\010\023\057\024\035\025\030\001\001" +
    "\000\010\023\056\024\035\025\030\001\001\000\010\023" +
    "\055\024\035\025\030\001\001\000\010\023\054\024\035" +
    "\025\030\001\001\000\010\023\053\024\035\025\030\001" +
    "\001\000\010\023\050\024\035\025\030\001\001\000\010" +
    "\023\051\024\035\025\030\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\064\001\001\000\004" +
    "\025\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\023\036\024\035\025\030\026\074\001" +
    "\001\000\012\023\036\024\035\025\030\026\073\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\006\104\007\102\010\106\011\105" +
    "\014\103\015\101\016\100\001\001\000\002\001\001\000" +
    "\014\006\104\007\102\010\106\011\105\016\112\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\023" +
    "\114\024\035\025\030\001\001\000\002\001\001\000\012" +
    "\023\036\024\035\025\030\026\116\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\006\104\007\102\010\106" +
    "\011\105\014\121\015\101\016\100\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\023\130\024" +
    "\035\025\030\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\017\137\020" +
    "\140\021\136\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\021\141\001\001\000\002\001" +
    "\001\000\014\022\151\023\147\024\035\025\030\027\150" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\023\155\024\035\025\030\001\001\000\002\001\001" +
    "\000\010\023\157\024\035\025\030\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private Lexer lex;
    private List<ErrorReporte> errorReportes = new ArrayList<>();
    private List<ReporteEstructura> estructuras = new ArrayList<>();

    public Parser(Lexer lex) {
        super(lex);
        this.lex = lex;
    }

    public Lexer getLexer() {
        return this.lex;
    }

    public List<ErrorReporte> getErrorReportes() {
        return errorReportes;
    }

    public void syntax_error(Symbol cur_token) {
        String lexema = symbl_name_from_id(cur_token.sym);
        if (cur_token.value != null) {
            lexema = lexema + " (" + cur_token.value.toString() + ")";
        }
        errorReportes.add(
            new ErrorReporte(lexema, cur_token.left, cur_token.right,
                    "Sintactico", "Token inesperado"));
    }

    public void report_error(String message, Object info){
        if (info instanceof Symbol) {
            Symbol cur_token = (Symbol) info;
            errorReportes.add(
                new ErrorReporte(
                    symbl_name_from_id(cur_token.sym),
                    cur_token.left,
                    cur_token.right,
                    "Sintactico",
                    message != null ? message : "Error sintactico"
                )
            );
        }
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        errorReportes.add(
            new ErrorReporte(
                symbl_name_from_id(cur_token.sym),
                cur_token.left,
                cur_token.right,
                "Sintactico",
                "Error sintactico fatal"
            )
        );
    }

    public List<ReporteEstructura> getEstructuras() {
        return estructuras;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoPrograma start_val = (NodoPrograma)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= seccion_pseudocodigo SEPARADOR_SECCION seccion_configuracion 
            {
              NodoPrograma RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoASTBase> p = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<NodoConfiguracion> c = (List<NodoConfiguracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoPrograma(0,0,p,c); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // seccion_pseudocodigo ::= INICIO lista_instrucciones FIN 
            {
              List<NodoASTBase> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoASTBase> l = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_pseudocodigo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              List<NodoASTBase> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoASTBase> l = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase i = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    l.add(i);
    RESULT = l;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_instrucciones ::= instruccion 
            {
              List<NodoASTBase> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase i = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    List<NodoASTBase> lista = new ArrayList<>();
    lista.add(i);
    RESULT = lista;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= declaracion 
            {
              NodoASTBase RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase d = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
    Log.d("ParserDebug", "Instruccion declaracion: " + d);
    RESULT = d;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= asignacion 
            {
              NodoASTBase RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase a = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= mostrar 
            {
              NodoASTBase RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase m = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = m; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= leer 
            {
              NodoASTBase RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase l = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= si_condicional 
            {
              NodoASTBase RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase s = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = s; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= mientras_ciclo 
            {
              NodoASTBase RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int wright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase w = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = w; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloque_simple ::= lista_instrucciones_simples 
            {
              List<NodoASTBase> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<NodoASTBase> l = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_simple",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_instrucciones_simples ::= lista_instrucciones_simples instruccion_simple 
            {
              List<NodoASTBase> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoASTBase> l = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase i = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(i);
                                        RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones_simples",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_instrucciones_simples ::= instruccion_simple 
            {
              List<NodoASTBase> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase i = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<NodoASTBase> lista = new ArrayList<>();
                                        lista.add(i);
                                        RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_instrucciones_simples",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion_simple ::= declaracion 
            {
              NodoASTBase RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase d = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instruccion_simple ::= asignacion 
            {
              NodoASTBase RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase a = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instruccion_simple ::= mostrar 
            {
              NodoASTBase RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase m = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = m; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // instruccion_simple ::= leer 
            {
              NodoASTBase RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase l = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_simple",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion ::= VAR IDENTIFICADOR OPERADOR_ASIGNACION expresion 
            {
              NodoASTBase RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoDeclaracion nodo = new NodoDeclaracion(idleft, idright, id, e);
                       RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracion ::= VAR IDENTIFICADOR 
            {
              NodoASTBase RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoDeclaracion nodo = new NodoDeclaracion(idleft, idright, id, null);
                        RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // asignacion ::= IDENTIFICADOR OPERADOR_ASIGNACION expresion 
            {
              NodoASTBase RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoAsignacion nodo = new NodoAsignacion(idleft, idright, id, e);
                        RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // mostrar ::= MOSTRAR CADENA 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoMostrar nodo = new NodoMostrar(cleft, cright, new NodoLiteral(cleft, cright, c));
                    RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // mostrar ::= MOSTRAR expresion 
            {
              NodoASTBase RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoMostrar nodo = new NodoMostrar(e.getLinea(), e.getColumna(), e);
                    RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // leer ::= LEER IDENTIFICADOR 
            {
              NodoASTBase RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 NodoLeer nodo = new NodoLeer(idleft, idright, id);
               RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("leer",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // si_condicional ::= SI LPAREN condicion RPAREN ENTONCES bloque_simple FINSI 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoASTBase> b = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 NodoSi nodo = new NodoSi(c.getLinea(), c.getColumna(), c, b);
                            RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("si_condicional",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // si_condicional ::= SI LPAREN condicion RPAREN ENTONCES bloque_simple FIN SI 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoASTBase> b = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new NodoSi(c.getLinea(), c.getColumna(), c, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("si_condicional",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // mientras_ciclo ::= MIENTRAS LPAREN condicion RPAREN HACER bloque_simple FINMIENTRAS 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoASTBase> b = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 NodoMientras nodo = new NodoMientras(c.getLinea(), c.getColumna(), c, b);
                            RESULT = nodo; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mientras_ciclo",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // mientras_ciclo ::= MIENTRAS LPAREN condicion RPAREN HACER bloque_simple FIN MIENTRAS 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<NodoASTBase> b = (List<NodoASTBase>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new NodoMientras(c.getLinea(), c.getColumna(), c, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mientras_ciclo",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // seccion_configuracion ::= lista_configuraciones 
            {
              List<NodoConfiguracion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<NodoConfiguracion> l = (List<NodoConfiguracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_configuracion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_configuraciones ::= lista_configuraciones configuracion 
            {
              List<NodoConfiguracion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<NodoConfiguracion> l = (List<NodoConfiguracion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoConfiguracion c = (NodoConfiguracion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 l.add(c);
                               RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_configuraciones",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_configuraciones ::= configuracion 
            {
              List<NodoConfiguracion> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoConfiguracion c = (NodoConfiguracion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<NodoConfiguracion> lista = new ArrayList<>();
                                lista.add(c);
                                RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_configuraciones",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // configuracion ::= CONFIG OPERADOR_ASIGNACION valor_config 
            {
              NodoConfiguracion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoConfiguracion(cleft, cright, c, v, null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // configuracion ::= CONFIG OPERADOR_ASIGNACION valor_config PIPE NUMERO 
            {
              NodoConfiguracion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoConfiguracion(cleft, cright, c, v, n.intValue()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("configuracion",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // valor_config ::= COLOR_HEX 
            {
              String RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = h; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // valor_config ::= COLOR_RGB 
            {
              String RESULT =null;
		int rgbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rgbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String rgb = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = rgb; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // valor_config ::= FIGURA 
            {
              String RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // valor_config ::= LETRA 
            {
              String RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // valor_config ::= NUMERO 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = n.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= expresion SUMA termino 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoExpresion(e1.getLinea(), e1.getColumna(), "+", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= expresion RESTA termino 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoExpresion(e1.getLinea(), e1.getColumna(), "-", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= termino 
            {
              NodoASTBase RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase t = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // termino ::= termino MULT factor 
            {
              NodoASTBase RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase t1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase f = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoExpresion(t1.getLinea(), t1.getColumna(), "*", t1, f); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // termino ::= termino DIV factor 
            {
              NodoASTBase RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase t1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase f = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoExpresion(t1.getLinea(), t1.getColumna(), "/", t1, f); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // termino ::= factor 
            {
              NodoASTBase RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase f = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // factor ::= NUMERO 
            {
              NodoASTBase RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Number n = (Number)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoLiteral(nleft, nright, n.toString()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // factor ::= IDENTIFICADOR 
            {
              NodoASTBase RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoVariable(idleft, idright, id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // factor ::= LPAREN expresion RPAREN 
            {
              NodoASTBase RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoASTBase e = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // condicion ::= expresion MENOR expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), "<", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // condicion ::= expresion MAYOR expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), ">", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // condicion ::= expresion MENOR_IGUAL expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), "<=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // condicion ::= expresion MAYOR_IGUAL expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), ">=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // condicion ::= expresion IGUALDAD expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), "==", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // condicion ::= expresion DISTINTO expresion 
            {
              NodoASTBase RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(e1.getLinea(), e1.getColumna(), "!=", e1, e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // condicion ::= condicion AND condicion 
            {
              NodoASTBase RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase c1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase c2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(c1.getLinea(), c1.getColumna(), "&&", c1, c2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // condicion ::= condicion OR condicion 
            {
              NodoASTBase RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase c1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase c2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(c1.getLinea(), c1.getColumna(), "||", c1, c2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // condicion ::= NOT_LOGICO condicion 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new NodoCondicion(c.getLinea(), c.getColumna(), "!", c, null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // condicion ::= LPAREN condicion RPAREN 
            {
              NodoASTBase RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		NodoASTBase c = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // COLOR_RGB ::= expresion COMA expresion COMA expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		NodoASTBase e1 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		NodoASTBase e2 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		NodoASTBase e3 = (NodoASTBase)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1.toString() + "," + e2.toString() + "," + e3.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("COLOR_RGB",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
