
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1_compi.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ERROR_IDENTIFICADOR_INVALIDO = 40;
  public static final int NUMERO = 38;
  public static final int DISTINTO = 28;
  public static final int MULT = 21;
  public static final int SI = 10;
  public static final int MOSTRAR = 16;
  public static final int RESTA = 20;
  public static final int LPAREN = 34;
  public static final int ENTONCES = 11;
  public static final int FIN = 8;
  public static final int NOT_LOGICO = 31;
  public static final int RPAREN = 35;
  public static final int CONFIG = 3;
  public static final int IDENTIFICADOR = 37;
  public static final int AND = 29;
  public static final int FINMIENTRAS = 15;
  public static final int IGUALDAD = 27;
  public static final int LETRA = 5;
  public static final int OR = 30;
  public static final int MIENTRAS = 13;
  public static final int DIV = 22;
  public static final int SUMA = 19;
  public static final int COLOR_HEX = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int CADENA = 36;
  public static final int PIPE = 33;
  public static final int MENOR = 23;
  public static final int ERROR = 39;
  public static final int MAYOR = 24;
  public static final int MAYOR_IGUAL = 26;
  public static final int ERROR_DECIMAL_INVALIDO = 41;
  public static final int LEER = 17;
  public static final int HACER = 14;
  public static final int OPERADOR_ASIGNACION = 18;
  public static final int INICIO = 7;
  public static final int MENOR_IGUAL = 25;
  public static final int FINSI = 12;
  public static final int VAR = 9;
  public static final int SEPARADOR_SECCION = 2;
  public static final int FIGURA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEPARADOR_SECCION",
  "CONFIG",
  "FIGURA",
  "LETRA",
  "COLOR_HEX",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "FINSI",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS",
  "MOSTRAR",
  "LEER",
  "OPERADOR_ASIGNACION",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUALDAD",
  "DISTINTO",
  "AND",
  "OR",
  "NOT_LOGICO",
  "COMA",
  "PIPE",
  "LPAREN",
  "RPAREN",
  "CADENA",
  "IDENTIFICADOR",
  "NUMERO",
  "ERROR",
  "ERROR_IDENTIFICADOR_INVALIDO",
  "ERROR_DECIMAL_INVALIDO"
  };
}

