package com.example.practica1_compi.analizadores;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 14;
  public static final int FIGURA = 4;
  public static final int CADENA = 18;
  public static final int RPAREN = 16;
  public static final int LETRA = 5;
  public static final int OPERADOR_RELACIONAL = 8;
  public static final int OPERADOR_ASIGNACION = 12;
  public static final int ERROR = 20;
  public static final int LPAREN = 15;
  public static final int COMA = 13;
  public static final int EOF = 0;
  public static final int SEPARADOR_SECCION = 2;
  public static final int OPERADOR_ARITMETICO = 11;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int OPERADOR_LOGICO = 9;
  public static final int NOT_LOGICO = 10;
  public static final int IDENTIFICADOR = 19;
  public static final int PALABRA_RESERVADA = 7;
  public static final int ERROR_DECIMAL_INVALIDO = 22;
  public static final int ERROR_IDENTIFICADOR_INVALIDO = 21;
  public static final int CONFIG = 3;
  public static final int COLOR_HEX = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEPARADOR_SECCION",
  "CONFIG",
  "FIGURA",
  "LETRA",
  "COLOR_HEX",
  "PALABRA_RESERVADA",
  "OPERADOR_RELACIONAL",
  "OPERADOR_LOGICO",
  "NOT_LOGICO",
  "OPERADOR_ARITMETICO",
  "OPERADOR_ASIGNACION",
  "COMA",
  "PIPE",
  "LPAREN",
  "RPAREN",
  "NUMERO",
  "CADENA",
  "IDENTIFICADOR",
  "ERROR",
  "ERROR_IDENTIFICADOR_INVALIDO",
  "ERROR_DECIMAL_INVALIDO"
  };
}

